IOP_BIN  = rapull.irx
IOP_OBJS = rapull.o imports.o

IOP_INCS += -I../common -I../../iopcore/common

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
