IOP_BIN  = raudp.irx
IOP_OBJS = raudp.o imports.o exports.o

IOP_INCS += -I../common -I../../iopcore/common

include $(PS2SDK)/Defs.make
include ../../Rules.bin.make
include $(PS2SDK)/samples/Makefile.iopglobal
